services:
  catalog.web:
    image: catalog.web
    build:
      context: .
      dockerfile: src/Catalog/Catalog.Web/Dockerfile

  membership.web:
    image: membership.web
    build:
      context: .
      dockerfile: src/Membership/Membership.Web/Dockerfile

